beauty_salon_web/appointments/urls.py
from django.urls import path

from appointments.views import (date_and_time, appointments_create, appointments, appointments_delete,
                                appointment_sale, date_and_time_edit, date_and_time_delete, date_delete, sale_add)

app_name = 'appointments'

urlpatterns = [
    path('date_and_time/<int:service_id>', date_and_time, name='date_and_time'),
    path('appointments_create/<int:time_id>/<int:service_id>', appointments_create, name='appointments_create'),
    path('appointments_create_sale/<int:time_id>/<int:service_id>/<int:sale_id>', appointments_create, name='appointments_create_sale'),
    path('appointments/<int:time_id>/<int:service_id>', appointments, name='appointments'),
    path('appointments_sale/<int:time_id>/<int:service_id>/<int:sale_id>', appointment_sale, name='appointments_sale'),
    path('appointments_delete/<int:app_id>', appointments_delete, name='appointments_delete'),
    path('date_and_time_edit/', date_and_time_edit, name='date_and_time_edit'),
    path('date_and_time_delete/<int:time_id>', date_and_time_delete, name='date_and_time_delete'),
    path('date_delete/<int:date_id>', date_delete, name='date_delete'),
    path('sale_add/', sale_add, name='sale_add'),
]

beauty_salon_web/beauty_salon_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from salon.views import index, service

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('service/', service, name='service'),
    path('category/<int:category_id>', service, name='category'),
    path('users/', include('users.urls', namespace='users')),
    path('appointments/', include('appointments.urls', namespace='appointments')),
    path('salon/', include('salon.urls', namespace='salon')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

beauty_salon_web/salon/urls.py
from django.urls import path

from salon.views import service_add, service_delete

app_name = 'salon'

urlpatterns = [
    path('service_add', service_add, name='service_add'),
    path('service_delete/<int:service_id>', service_delete, name='service_delete'),
]

beauty_salon_web/appointments/models.py
from django.db import models

from users.models import User
from salon.models import Service

#Модель для хранения и работы с датами
class DateTable(models.Model):
    date = models.DateField()

    def __str__(self):
        return str(self.date)

#Модель записей на сайте
class TimeTable(models.Model):
    FREE = 0
    OCCUPIED = 1
    STATUSES = (
        (FREE, 'Свободно'),
        (OCCUPIED, 'Занято')
    )

    date = models.ForeignKey(DateTable, on_delete=models.CASCADE)
    time_start = models.TimeField()
    time_end = models.TimeField()
    status = models.SmallIntegerField(choices=STATUSES, default=FREE)

    def __str__(self):
        return f'Дата:{self.date.date} Время: {self.time_start} - {self.time_end} | Статус: {self.status}'

#Модель скидки
class Sale(models.Model):
    name = models.CharField(max_length=256)
    percent = models.IntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

#Модель записи клиента
class Appointment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time = models.ForeignKey(TimeTable, on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    price = models.IntegerField(default=0, blank=True, null=True)

beauty_salon_web/appointments/forms.py
from django import forms

from appointments.models import DateTable, TimeTable, Sale
from users.models import User


class DateForm(forms.ModelForm):
    date = forms.DateField(widget=forms.DateInput(
        attrs={
            'class': 'input-form',
            'placeholder': 'Введите дату'
        }
    ))

    class Meta:
        model = DateTable
        fields = ('date', )


class TimeForm(forms.ModelForm):
    date = forms.ModelChoiceField(widget=forms.Select(
        attrs={
            'class': 'input-form',
            'placeholder': 'Выберите дату'
        }
    ), queryset=DateTable.objects.all())
    time_start = forms.TimeField(widget=forms.TimeInput(
        attrs={
            'class': 'input-form',
            'placeholder': 'Введите начало периода'
        }

    ))
    time_end = forms.TimeField(widget=forms.TimeInput(
        attrs={
            'class': 'input-form',
            'placeholder': 'Введите конец периода'
        }
    ))

    class Meta:
        model = TimeTable
        fields = ('date', 'time_start', 'time_end')


class SaleForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'input-form',
            'placeholder': 'Введите название скидки'
        }
    ))
    percent = forms.IntegerField(widget=forms.NumberInput(
        attrs={
            'class': 'input-form',
            'placeholder': 'Введите процент скидки (в процентах)'
        }
    ))
    user = forms.ModelChoiceField(widget=forms.Select(
        attrs={
            'class': 'input-form',
            'placeholder': 'Выберите дату'
        }
    ), queryset=User.objects.filter(is_superuser=False))

    class Meta:
        model = Sale
        fields = ('name', 'percent', 'user')

beauty_salon_web/appointments/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from appointments.models import Appointment, DateTable, TimeTable, Sale
from salon.models import Service
from appointments.forms import DateForm, TimeForm, SaleForm

#Отображение страницы выбора даты и времени для записи на услугу
@login_required
def date_and_time(request, service_id):
    time = TimeTable.objects.all()
    date = DateTable.objects.all()
    service = Service.objects.get(id=service_id)

    context = {
        'time': time,
        'title': 'Выбор времени',
        'date': date,
        'service': service,
    }
    return render(request, 'appointments/date-and-time.html', context)

#Отображение страницы редактирования расписания, где пользователь
#может добавлять и редактировать даты и времена записей на услугу.
@login_required
def date_and_time_edit(request):
    time = TimeTable.objects.all()
    date = DateTable.objects.all()

    if request.method == 'POST':
        form_date = DateForm(data=request.POST, files=request.FILES)
        if form_date.is_valid():
            form_date.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        form_date = DateForm()

    if request.method == 'POST':
        form_time = TimeForm(data=request.POST, files=request.FILES)
        if form_time.is_valid():
            form_time.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        form_time = TimeForm()

    context = {
        'time': time,
        'title': 'Редактор раписания',
        'date': date,
        'form_date': form_date,
        'form_time': form_time
    }
    return render(request, 'appointments/date-and-time-edit.html', context)

#Удаление времени и даты записи из расписания
@login_required
def date_and_time_delete(request, time_id):
    time = TimeTable.objects.get(id=time_id)
    time.delete()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def date_delete(request, date_id):
    date = DateTable.objects.get(id=date_id)
    date.delete()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

#Запись на услугу
@login_required
def appointments(request, time_id, service_id):
    time = TimeTable.objects.get(id=time_id)
    service = Service.objects.get(id=service_id)
    sales = Sale.objects.filter(user=request.user)

    context = {
        'time': time,
        'service': service,
        'title': 'Запись',
        'sales': sales,
    }
    return render(request, 'appointments/appointment.html', context)

#Запись на услугу с применением скидки
@login_required
def appointment_sale(request, time_id, service_id, sale_id):
    time = TimeTable.objects.get(id=time_id)
    service = Service.objects.get(id=service_id)

    sale = Sale.objects.get(id=sale_id)
    sale_percent = sale.percent
    service_price = service.price
    price = int(service_price) - sale_percent / 100 * int(service_price)

    context = {
        'time': time,
        'service': service,
        'title': 'Запись',
        'price': price,
        'sale': sale,
    }
    return render(request, 'appointments/appointments_sale.html', context)

#Создание записи администратором
@login_required
def appointments_create(request, time_id, service_id, sale_id=None):
    time = TimeTable.objects.get(id=time_id)
    service = Service.objects.get(id=service_id)

    appointment = Appointment()
    appointment.time = time
    appointment.service = service
    appointment.user = request.user

    if sale_id:
        sale = Sale.objects.get(id=sale_id)
        sale_percent = sale.percent
        service_price = service.price
        price = int(service_price) - sale_percent / 100 * int(service_price)
        appointment.price = price
        appointment.save()
        sale.delete()
    else:
        appointment.price = service.price
        appointment.save()

    time.status = 1
    time.save()

    return HttpResponseRedirect(reverse('users:profile'))

#Удаление записи администратором
@login_required
def appointments_delete(request, app_id):
    appointment = Appointment.objects.get(id=app_id)
    time = TimeTable.objects.get(id=appointment.time.id)
    time.status = 0
    time.save()

    appointment.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

#Добавление скидки администратором
def sale_add(request):
    if request.method == 'POST':
        form = SaleForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        form = SaleForm()

    sales = Sale.objects.all()

    context = {
        'title': 'Скидки',
        'sales': sales,
        'form': form
    }
    return render(request, 'appointments/sale_add.html', context)

beauty_salon_web/appointments/templates/appointments/appointment.html
{% extends 'salon/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/appointment.css' %}">
{% endblock %}

{% block main %}
    <section class="appointment-create-container">
        <h1 class="appointment-name">Услуга: {{ service.name }}</h1>
        <p class="appointment-date">Дата записи: {{ time.date.date }} : {{ time.time_start }} - {{ time.time_end }}</p>
        <p class="appointment-price">Цена: {{ service.price }}</p>
        <a href="{% url 'appointments:appointments_create' time.id service.id %}" class="appointment-create-link">Записаться</a>
    </section>
    {% if sales %}
            <div class="sale-container">
                <div class="sale-title">Доступные скидки:</div>
                {% for sale in sales %}
                <div class="sale-item">
                    <div class="sale-name">{{ sale.name }}</div>
                    <div class="sale-percent">Скидка: {{ sale.percent }} %</div>
                    <a href="{% url 'appointments:appointments_sale' time.id service.id sale.id  %}" class="link-sale">Применит скидку</a>
                </div>
                {% endfor %}
            </div>
        {% endif %}
{% endblock %}

beauty_salon_web/appointments/templates/appointments/appointments_sale.html
{% extends 'salon/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/appointment.css' %}">
{% endblock %}

{% block main %}
    <section class="appointment-create-container">
        <h1 class="appointment-name">Услуга: {{ service.name }}</h1>
        <p class="appointment-date">Дата записи: {{ time.date.date }} : {{ time.time_start }} - {{ time.time_end }}</p>
        <p class="appointment-price">Цена (с учетом скидки): {{ price }}</p>
        <a href="{% url 'appointments:appointments_create_sale' time.id service.id sale.id %}" class="appointment-create-link">Записаться</a>
    </section>
{% endblock %}

beauty_salon_web/appointments/templates/appointments/date-and-time-edit.html
{% extends 'salon/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/date-and-time.css' %}">
{% endblock %}

{% block main %}
    <section class="timetable-container">
        <h1 class="timetable-title">Доступные промежутки времени</h1>
        <div class="timetable-list">
            {% if time %}
                {% for date in date %}
                <div class="timetable-item">
                    <h2 class="timetable-date">Дата: {{ date }}</h2>
                    <div class="timetable-time-list">
                        <p class="timetable-time-title">Доступное время:</p>
                        {% for time in time %}
                            {% if time.date == date %}
                                {% if time.status == 0 %}
                                <div class="timetable-time-item">
                                    <span class="timetable-time">{{ time.time_start }} - {{ time.time_end }}</span>
                                    <a href="{% url 'appointments:date_and_time_delete' time.id %}" class="link-delete">Удалить</a>
                                </div>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    </div>
                    <a href="{% url 'appointments:date_delete' date.id %}" class="link-delete">Удалить дату</a>
                </div>
                {% endfor %}
            {% else %}
                <span>Нет доступного времени для записи</span>
            {% endif %}
        </div>
    </section>
    <section class="date-and-time-add">
        <div class="date-add-container">
            <h2 class="date-add-title">Добавить новую дату в расписание</h2>
            <form action="{% url 'appointments:date_and_time_edit' %}" method="post">
                {% csrf_token %}
                <div class="form-block">
                    <label for="{{ form_date.date.id_for_label }}" class="label-form">Выберите дату (дата.месяц.год)</label>
                    {{ form_date.date }}
                </div>
                <div class="form-block">
                    <button type="submit" class="btn-form">Добавить</button>
                </div>
            </form>
        </div>
        <div class="time-add-container">
            <h2 class="time-add-title">Добавить новое время в расписание</h2>
            <form action="{% url 'appointments:date_and_time_edit' %}" method="post">
                {% csrf_token %}
                <div class="form-block">
                    <label for="{{ form_time.date.id_for_label }}" class="label-form">Выберите дату</label>
                    {{ form_time.date }}
                </div>
                <div class="form-block">
                    <label for="{{ form_time.time_start.id_for_label }}" class="label-form">Выберите начало</label>
                    {{ form_time.time_start }}
                </div>
                <div class="form-block">
                    <label for="{{ form_time.time_end.id_for_label }}" class="label-form">Выберите конец</label>
                    {{ form_time.time_end }}
                </div>
                <div class="form-block">
                    <button type="submit" class="btn-form">Добавить</button>
                </div>
            </form>
        </div>
    </section>
{% endblock %}

beauty_salon_web/appointments/templates/appointments/date-and-time.html
{% extends 'salon/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/date-and-time.css' %}">
{% endblock %}

{% block main %}
    <section class="timetable-container">
        <h1 class="timetable-title">Выберите свободный промежуток времени</h1>
        <div class="timetable-list">
            {% if time %}
                {% for date in date %}
                <div class="timetable-item">
                    <h2 class="timetable-date">Дата: {{ date }}</h2>
                    <div class="timetable-time-list">
                        <p class="timetable-time-title">Доступное время:</p>
                        {% for time in time %}
                            {% if time.date == date %}
                                {% if time.status == 0 %}
                                <div class="timetable-time-item">
                                    <span class="timetable-time">{{ time.time_start }} - {{ time.time_end }}</span>
                                    <a href="{% url 'appointments:appointments' time.id service.id %}" class="advertisement-link">Записаться</a>
                                </div>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
                {% endfor %}
            {% else %}
                <span>Нет доступного времени для записи</span>
            {% endif %}
        </div>
    </section>
{% endblock %}

beauty_salon_web/appointments/templates/appointments/sale_add.html
{% extends 'salon/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/sale_add.css' %}">
{% endblock %}

{% block main %}
    <section class="sale-container">
        <h1 class="sale-title">Все скидки в системе</h1>
        <div class="sale-list">
            {% if sales %}
                {% for sale in sales %}
                    <div class="sale-item">
                        <p class="sale-name">{{ sale.name }}</p>
                        <p class="sale-percent">Скидка: {{ sale.percent }} %</p>
                        <p class="sale-user">Доступна для пользователя: {{ sale.user.first_name }} {{ sale.user.second_name }}</p>
                        <a href="" class="link-delete">Удалить</a>
                    </div>
                {% endfor %}
            {% else %}
                <p class="message">В системе нет скидок</p>
            {% endif %}
        </div>
    </section>
    <section class="sale-add-container">
           <form action="{% url 'appointments:sale_add' %}" method="post" class="form">
               <h2 class="form-title">Добавить скидку</h2>
                {% csrf_token %}
                <div class="form-block">
                    <label for="{{ form.name.id_for_label }}" class="label-form">Название скидочной акции</label>
                    {{ form.name }}
                </div>
                <div class="form-block">
                    <label for="{{ form.percent.id_for_label }}" class="label-form">Процент скидки</label>
                    {{ form.percent }}
                </div>
                <div class="form-block">
                    <label for="{{ form.user.id_for_label }}" class="label-form">Получатель скидки</label>
                    {{ form.user }}
                </div>
                <div class="form-block-btn">
                    <button type="submit" class="btn-form">Добавить</button>
                </div>
            </form>
        </section> 
{% endblock %}