beauty_salon_web/appointments/urls.py
from django.urls import path

from appointments.views import (date_and_time, appointments_create, appointments, appointments_delete,
                                appointment_sale, date_and_time_edit, date_and_time_delete, date_delete, sale_add)

app_name = 'appointments'

urlpatterns = [
    path('date_and_time/<int:service_id>', date_and_time, name='date_and_time'),
    path('appointments_create/<int:time_id>/<int:service_id>', appointments_create, name='appointments_create'),
    path('appointments_create_sale/<int:time_id>/<int:service_id>/<int:sale_id>', appointments_create, name='appointments_create_sale'),
    path('appointments/<int:time_id>/<int:service_id>', appointments, name='appointments'),
    path('appointments_sale/<int:time_id>/<int:service_id>/<int:sale_id>', appointment_sale, name='appointments_sale'),
    path('appointments_delete/<int:app_id>', appointments_delete, name='appointments_delete'),
    path('date_and_time_edit/', date_and_time_edit, name='date_and_time_edit'),
    path('date_and_time_delete/<int:time_id>', date_and_time_delete, name='date_and_time_delete'),
    path('date_delete/<int:date_id>', date_delete, name='date_delete'),
    path('sale_add/', sale_add, name='sale_add'),
]

beauty_salon_web/beauty_salon_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from salon.views import index, service

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('service/', service, name='service'),
    path('category/<int:category_id>', service, name='category'),
    path('users/', include('users.urls', namespace='users')),
    path('appointments/', include('appointments.urls', namespace='appointments')),
    path('salon/', include('salon.urls', namespace='salon')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

beauty_salon_web/salon/urls.py
from django.urls import path

from salon.views import service_add, service_delete

app_name = 'salon'

urlpatterns = [
    path('service_add', service_add, name='service_add'),
    path('service_delete/<int:service_id>', service_delete, name='service_delete'),
]

beauty_salon_web/users/urls.py
from django.urls import path

from users.views import login, registration, profile, logout, admin_panel

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
    path('admin_panel/', admin_panel, name='admin_panel'),
]

beauty_salon_web/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

#Модель пользователя
class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)

beauty_salon_web/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'placeholder': 'Введите имя пользователя',
            'class': 'form-input'
        }
    ))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'placeholder': 'Введите пароль',
            'class': 'form-input'
        }))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'placeholder': 'Введите имя',
            'class': 'form-input'
        }
    ))
    last_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'placeholder': 'Введите фамилию',
            'class': 'form-input'
        }
    ))
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'placeholder': 'Введите имя пользователя',
            'class': 'form-input'
        }
    ))
    email = forms.CharField(widget=forms.EmailInput(
        attrs={
            'placeholder': 'Введите адрес эл. почты',
            'class': 'form-input'
        }
    ))
    phone = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-input',
            'placeholder': 'Введите номер телефона'
        }
    ))
    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'placeholder': 'Введите пароль',
            'class': 'form-input'
        }
    ))
    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'placeholder': 'Подтвердите пароль',
            'class': 'form-input'
        }
    ))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'phone', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-input'
        }
    ))
    last_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-input'
        }
    ))
    image = forms.ImageField(widget=forms.FileInput(
        attrs={
            'class': 'custom-file-input',
        }
    ), required=False)
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-input',
            'readonly': True
        }
    ))
    email = forms.CharField(widget=forms.EmailInput(
        attrs={
            'class': 'form-input',
        }
    ))
    phone = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-input',
        }
    ))


    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'image', 'username', 'email', 'phone')

beauty_salon_web/users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib import messages, auth
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm
from appointments.models import Appointment, Sale

#Авторизация
def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('index'))
    else:
        form = UserLoginForm()
    context = {
        'title': 'Авторизация',
        'form': form,
    }
    return render(request, 'users/login.html', context)

#Регистрация
def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            user = form.save()

            sale = Sale()
            sale.name = 'Скидка на первый заказ 20%'
            sale.user = user
            sale.percent = 20
            sale.save()

            messages.success(request, 'Регистрация прошла успешно!')
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegistrationForm
    context = {
        'title': 'Регистрация',
        'form': form,
    }
    return render(request,'users/registration.html', context)

#Просмотр профиля
@login_required
def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(instance=request.user, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = UserProfileForm(instance=request.user)

    context = {
        'title': 'Профиль',
        'form': form,
        'appointment': Appointment.objects.filter(user=request.user),
        'sales': Sale.objects.filter(user=request.user),
    }
    return render(request, 'users/profile.html', context)

#Выход из профиля
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))

#Панель администратора
def admin_panel(request):
    context = {
        'title': 'Панель администратора'
    }
    return render(request, 'users/admin-panel.html', context)

beauty_salon_web/users/templates/users/admin-panel.html
{% extends 'salon/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/admin-panel.css' %}">
{% endblock %}

{% block main %}
    <section class="admin-panel-container">
        <a href="{% url 'salon:service_add' %}" class="link-admin">Добавить услугу</a>
        <a href="{% url 'appointments:date_and_time_edit' %}" class="link-admin">Редактировать расписание</a>
        <a href="{% url 'appointments:sale_add' %}" class="link-admin">Добавить скидку</a>
        <a href="{% url 'admin:index' %}" class="link-admin">Панель Django</a>
    </section>
{% endblock %}

beauty_salon_web/users/templates/users/login.html
{% extends 'salon/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block main %}
    <section class="login-container">
        <div class="auth-title">Авторизация</div>
        <form action="{% url 'users:login' %}" method="post" class="auth-form">
            {% csrf_token %}
            <div class="form-group">
                <label class="form-label" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                {{ form.username }}
            </div>
            <div class="form-group">
                <label class="form-label" for="{{ form.password.id_for_label }}">Пароль</label>
                {{ form.password }}
            </div>
            <div class="form-nav">
                <input class="auth-button" type="submit" value="Авторизоваться">
            </div>
        </form>
        <div class="registration-container">
            <a href="{% url 'users:registration' %}" class="reg-button">Нужен аккаунт? Зарегистрируйся!</a>
        </div>
    </section>
    {% if messages or form.non_field_errors %}
        <div class="{% if messages %}container-successful{% else %}container-errors{% endif %}">
            {% if messages %}
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            {% else %}
                {{ form.non_field_errors }}
            {% endif %}
        </div>
        {% endif %}
{% endblock %}

beauty_salon_web/users/templates/users/profile.html
{% extends 'salon/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock %}

{% block main %}
    <section class="profile-container">
        <form action="{% url 'users:profile' %}" method="post" class="profile-form" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="profile-avatar-container">
                <img src="{% if user.image %}
                    {{ user.image.url }}
                {% else %}
                    {% static 'img/avatar.jpg' %}
                {% endif %}" alt="avatar" class="profile-avatar">
                <div class="form-change-image">
                    {{ form.image }}
                    <label class="custom-file-label" for="{{ form.image.id_for_label }}">Изменить изображение</label>
                </div>
            </div>
            <div class="profile-info">
                <div class="form-group">
                    <label class="form-label" for="{{ form.first_name.id_for_label }}">Имя</label>
                    {{ form.first_name }}
                </div>
                <div class="form-group">
                    <label class="form-label" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                    {{ form.last_name }}
                </div>
                <div class="form-group">
                    <label class="form-label" for="{{ form.phone.id_for_label }}">Номер телефона</label>
                    {{ form.phone }}
                </div>
                <div class="form-group">
                    <label class="form-label" for="{{ form.email.id_for_label }}">Адрес электронной почты</label>
                    {{ form.email }}
                </div>
                <div class="form-group">
                    <label class="form-label" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                    {{ form.username }}
                </div>
                <div class="form-save">
                    <input class="form-save-btn" type="submit" value="Сохранить">
                </div>
            </div>
        </form>
    </section>
    <section class="sale-container">
        <h2 class="sale-title">Мои скидки</h2>
        {% if sales %}
            {% for sale in sales %}
                <div class="sale-item">
                    <div class="sale-name">{{ sale.name }}</div>
                    <div class="sale-percent">Скидка: {{ sale.percent }} %</div>
                    <a href="{% url 'service' %}" class="link-sale">Применит скидку</a>
                </div>
            {% endfor %}
        {% else %}
            <p class="message">У вас нет доступных скидок</p>
        {% endif %}
    </section>
    <section class="appointments-container">
        <h2 class="appointments-title">Мои записи</h2>
        {% if appointment %}
            {% for app in appointment %}
                <div class="appointment-item">
                    <h3 class="appointment-name">{{ app.service.name }}</h3>
                    <p class="appointment-date">Дата: {{ app.time.date.date }}: {{ app.time.time_start }} - {{ app.time.time_end }}</p>
                    <p class="appointment-price">Цена: {{ app.price }} руб.</p>
                    <a href="{% url 'appointments:appointments_delete' app.id %}" class="link-reverse">Отменить запись</a>
                </div>
            {% endfor %}
        {% else %}
            <p class="message">У вас еще нет записей</p>
        {% endif %}
    </section>
{% endblock %}

beauty_salon_web/users/templates/users/registration.html
{% extends 'salon/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/registration.css' %}">
{% endblock %}

{% block main %}
    <section class="reg-container">
        <div class="reg-title">Регистрация</div>
        <form action="{% url 'users:registration' %}" method="post" class="reg-form">
            {% csrf_token %}
            <div class="form-group">
                <label class="form-label" for="{{ form.first_name.id_for_label }}">Имя</label>
                {{ form.first_name }}
            </div>
            <div class="form-group">
                <label class="form-label" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                {{ form.last_name }}
            </div>
            <div class="form-group">
                <label class="form-label" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                {{ form.username }}
            </div>
            <div class="form-group">
                <label class="form-label" for="{{ form.email.id_for_label }}">Адрес электронной почты</label>
                {{ form.email }}
            </div>
            <div class="form-group">
                <label class="form-label" for="{{ form.phone.id_for_label }}">Номер телефона</label>
                {{ form.phone }}
            </div>
            <div class="form-group">
                <label class="form-label" for="{{ form.password1.id_for_label }}">Пароль</label>
                {{ form.password1 }}
            </div>
            <div class="form-group">
                <label class="form-label" for="{{ form.password2.id_for_label }}">Подтверждение пароля</label>
                {{ form.password2 }}
            </div>
            <div class="form-nav">
                <input class="reg-button" type="submit" value="Создать аккаунт">
            </div>
        </form>
        <div class="registration-container">
            <a href="{% url 'users:login' %}" class="auth-button">Уже есть аккаунт? Авторизоваться</a>
        </div>
    </section>
    {% if form.errors %}
    <div class="container-errors">
        {{ form.errors }}
    </div>
    {% endif %}
{% endblock %}