beauty_salon_web/appointments/urls.py
from django.urls import path

from appointments.views import (date_and_time, appointments_create, appointments, appointments_delete,
                                appointment_sale, date_and_time_edit, date_and_time_delete, date_delete, sale_add)

app_name = 'appointments'

urlpatterns = [
    path('date_and_time/<int:service_id>', date_and_time, name='date_and_time'),
    path('appointments_create/<int:time_id>/<int:service_id>', appointments_create, name='appointments_create'),
    path('appointments_create_sale/<int:time_id>/<int:service_id>/<int:sale_id>', appointments_create, name='appointments_create_sale'),
    path('appointments/<int:time_id>/<int:service_id>', appointments, name='appointments'),
    path('appointments_sale/<int:time_id>/<int:service_id>/<int:sale_id>', appointment_sale, name='appointments_sale'),
    path('appointments_delete/<int:app_id>', appointments_delete, name='appointments_delete'),
    path('date_and_time_edit/', date_and_time_edit, name='date_and_time_edit'),
    path('date_and_time_delete/<int:time_id>', date_and_time_delete, name='date_and_time_delete'),
    path('date_delete/<int:date_id>', date_delete, name='date_delete'),
    path('sale_add/', sale_add, name='sale_add'),
]

beauty_salon_web/beauty_salon_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from salon.views import index, service

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('service/', service, name='service'),
    path('category/<int:category_id>', service, name='category'),
    path('users/', include('users.urls', namespace='users')),
    path('appointments/', include('appointments.urls', namespace='appointments')),
    path('salon/', include('salon.urls', namespace='salon')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

beauty_salon_web/salon/urls.py
from django.urls import path

from salon.views import service_add, service_delete

app_name = 'salon'

urlpatterns = [
    path('service_add', service_add, name='service_add'),
    path('service_delete/<int:service_id>', service_delete, name='service_delete'),
]

beauty_salon_web/users/urls.py
from django.urls import path

from users.views import login, registration, profile, logout, admin_panel

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
    path('admin_panel/', admin_panel, name='admin_panel'),
]

beauty_salon_web/salon/models.py
from django.db import models


class Category(models.Model): #Модель категорий услуг
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name

#Модель услуг
class Service(models.Model):
    name = models.CharField(max_length=256)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f'{self.name} | Категория: {self.category.name}'

beauty_salon_web/salon/forms.py
from django import forms

from salon.models import Service, Category


class ServiceForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-input',
            'placeholder': 'Введите наименование услуги'
        }))
    category = forms.ModelChoiceField(widget=forms.Select(
        attrs={
            'class': 'form-input',
            'placeholder': 'Выберите категорию услуги'
        }), queryset=Category.objects.all(), required=False)
    price = forms.DecimalField(widget=forms.TextInput(
        attrs={
            'class': 'form-input',
            'placeholder': 'Введите цену услуги'
        }))

    class Meta:
        model = Service
        fields = ('name', 'category', 'price')

beauty_salon_web/salon/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from salon.models import Category, Service
from salon.forms import ServiceForm

#Отображение главное страницы
def index(request):
    context = {
        'title': 'Главная'
    }
    return render(request, 'salon/index.html', context)

#Отображение страницы с услугами, фильтруя их по категории,
#если передан соответствующий идентификатор категории.
def service(request, category_id=None):
    if category_id:
        category = Category.objects.get(id=category_id)
        services = Service.objects.filter(category=category)
    else:
        services = Service.objects.all()

    context = {
        'title': 'Услуги',
        'services': services,
        'categoty': Category.objects.all()
    }
    return render(request, 'salon/service.html', context)


#Добавление товара (услуги) администротором
@login_required
def service_add(request):
    if request.method == 'POST':
        form = ServiceForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        form = ServiceForm()

    context = {
        'title': 'Добавить товар',
        'form': form,
    }
    return render(request, 'salon/service-add.html', context)


#Удаление товара (услуги) администратором
@login_required
def service_delete(request, service_id=None):
    service = Service.objects.get(id=service_id)
    service.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

beauty_salon_web/salon/templates/salon/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block css %}{% endblock %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">   
    <title>{{ title }}</title>
</head>
<body>
    <header>
        <nav>
            <div class="logo-container">
                <a href="{% url 'index' %}" class="logo">INNAN</a>
            </div>
            <div class="nav-list">
                <a href="{% url 'index' %}" class="nav-link">Главная</a>
                <a href="{% url 'service' %}" class="nav-link">Услуги</a>
                {% if user.is_authenticated %}
                    {% if user.is_superuser or user.is_staff %}
                        <a href="{% url 'users:admin_panel' %}" class="nav-link">Админ-панель</a>
                        <a href="{% url 'users:logout' %}" class="nav-link">Выход</a>
                    {% else %}
                        <a href="{% url 'users:profile' %}" class="nav-link">Профиль</a>
                        <a href="{% url 'users:logout' %}" class="nav-link">Выход</a>
                    {% endif %}
                {% else %}
                    <a href="{% url 'users:login' %}" class="nav-link">Вход</a>
                {% endif %}
            </div>
        </nav>
    </header>
    <main>
        {% block main %}
            
        {% endblock %}
    </main>
</body>
</html>

beauty_salon_web/salon/templates/salon/index.html
{% extends 'salon/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block main %}
    <section class="desc-container">
        <div class="desc-title-container">
            <h1 class="desc-title">INNAN — новая студия<br>красоты в сердце Казани</h1>
            <a href="{% url 'service' %}" class="desc-link">К выбору услуг</a>
        </div>
        <div class="desc-img-container">
            <img src="{% static 'img/desc-background.png' %}" alt="desc-background" class="desc-img">
        </div>
    </section>
{% endblock %}

beauty_salon_web/salon/templates/salon/service-add.html
{% extends 'salon/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/service-add.css' %}">
{% endblock %}

{% block main %}
    <section class="service-add-container">
        <form action="{% url 'salon:service_add' %}" method="post" class="service-form">
            {% csrf_token %}
            <div class="service-add">
                <div class="form-group">
                    <label class="form-label" for="{{ form.name.id_for_label }}">Наименование услуги</label>
                    {{ form.name }}
                </div>
                <div class="form-group">
                    <label class="form-label" for="{{ form.category.id_for_label }}">Категория услуги</label>
                    {{ form.category }}
                </div>
                <div class="form-group">
                    <label class="form-label" for="{{ form.price.id_for_label }}">Цена за услугу</label>
                    {{ form.price }}
                </div>
            </div>
            <div class="form-save">
                <input class="form-save-btn" type="submit" value="Добавить услугу">
            </div>
        </form>
    </section>
{% endblock %}

beauty_salon_web/salon/templates/salon/service.html
{% extends 'salon/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/service.css' %}">
{% endblock %}

{% block main %}
    <section class="services-container">
        <div class="category-container">
            <div class="category-list">
                {% for cat in categoty %}
                <div class="category-item">
                    <a href="{% url 'category' cat.id %}" class="category-link">{{ cat.name }}</a>
                </div>
                {% endfor %}
                <div class="category-item">
                    <a href="{% url 'service' %}" class="category-link">Все услуги</a>
                </div>
            </div>
        </div>
        <div class="service-container">
            <div class="service-list">
                {% for service in services %}
                    <div class="service-item">
                        <h2 class="service-name">{{ service.name }}</h2>
                        <span class="service-price">от {{ service.price }} руб.</span>
                        <div class="link-service-container">
                            {% if user.is_superuser or user.is_staff %}
                            <a href="{% url 'salon:service_delete' service.id %}" class="link-service">Удалить</a>
                            {% else %}
                            <a href="{% url 'appointments:date_and_time' service.id %}" class="link-service">Записаться</a>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}